# Plugins
gems:
- jekyll-sitemap
- jekyll-redirect-from
safe: false

# Build Settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Technology Robotix Society"
email: "contact@robotix.in"
description: "Technology Robotix Society"
baseurl: "http://www.robotix.in"
permalink: "/blog/:title"
collections:
  events:
    output: true
    permalink: "/event/:path/"
  tutorials:
    output: true
    permalink: "/tutorial/:path/"

# Analytics
googleAnalyticsTrackingId: "UA-33668522-1"
googleAnalyticsSiteUrl: "robotix.in"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Head
metaKeywords: "robotix, robotics, iit, kgp"
twitterAccount: "@robotixiitkgp"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/event/", text: "Events"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/about-us/", text: "About Us"}
 - {permalink: "/alumni/", text: "Alumni"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/spreadsheet/viewform?formkey=dHRMTVBfemdCaUZyX24zN3dkUkJwZGc6MQ#gid=0", text: "Contact Us"}
rightNavigationButtons:
 - {link: "https://docs.google.com/spreadsheet/viewform?formkey=dHRMTVBfemdCaUZyX24zN3dkUkJwZGc6MQ#gid=0", text: "Contact Us"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "29th Jan - 31st Jan, 2016"
typeoutTextValues: '"Technology Robotics^250 er..^250", "Technology Robotix Society", "Where Machines Dare!", "#GearUp", "Robotix 2016"'
typeoutFallback: "Technology Robotix Society"
heroButtons:
 - {permalink: "/event", text: "Explore our events"}
 - {permalink: "/#latest-blog", text: "Explore our blog"}

# About Block
aboutTitle: "We believe in sharing our knowledge"
aboutBlock:
 - {title: "K.R.A.I.G.", image: "conference.jpg", text: "Kickstart your journey into the world of hobby robotics." }
 - {title: "K.R.I.S.S.", image: "workshop.jpg", text: "To bring together people, to discuss and exchange ideas related to more mature and nuanced areas of robotics." }
 - {title: "Workshops", image: "hackathon.jpg", text: "Contact us, Invite us, Get a workshop organized at your college/university!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "2000", specialCharacter: "+", info: "participants"}
 - {count: "500", specialCharacter: "+", info: "teams"}
 - {count: "6", specialCharacter: "", info: "events"}
 - {count: "1", specialCharacter: "", info: "fest"}

# Latest News Block
latestNewsTitle: "Latest blog articles"
latestNewsCount: 2
latestNewsButtonText: "Explore our blog"

# Facebook Feed Block
FbFeedTitle: "Are You Geared Up?"
FbHashTag: "robotixiitkgp"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://robotix.us8.list-manage.com/subscribe/post?u=175d25a13bb44ffe7478a4ccf&amp;id=8de4186fe7"
subscribeInfo: "Subscribe with us to stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/102868621563384739622/", icon: "google-plus"}
 - {link: "https://twitter.com/RobotixIITKgp", icon: "twitter"}
 - {link: "https://facebook.com/robotixiitkgp", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://play.google.com/store/apps/details?id=in.robotix.robotixapp", text: "Robotix App"}
   - {link: "http://robotix.in/event/", text: "Events"}
   - {link: "http://robotix.in/tutorial/", text: "Tutorials"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@robotix.in", text: "contact@robotix.in"}

# Blog
blogCommentsEnabled: true
discusShortName: "robotix"

# Speakers List Block
showSessions: true

#AboutUs
whoAreWe: "Technology Robotix Society is an official society under the Technology Students' Gymkhana, IIT Kharagpur, and is a focal point for activities and projects related to robotics in the campus. With its reach expanding steadily each year, it has also cemented its position as one of the nerve centres of amateur robotics in India."
whatDoWeDo: "We are involved in various initiatives in the field of robotics throughout the year. Our flagship accomplishment is our annual competition ROBOTIX, which is held during KSHITIJ at IIT Kharagpur, and is one of the biggest such events in Asia. Every year we have increasingly capable and motivated participants tackling our novel problem statements and thereby inspiring us to organize each year's fest with renewed zeal. Another important agenda of ours is to spread the culture of robotics across India and we do this by organizing and conducting workshops and demonstrations, and in Kharagpur, besides this, by other in-house events too."
